### ISSUE TITLE
School specific themes

### ISSUE THREAD

**Issue by Apexal** [Apexal/examen#32]
**Using CSS variables:**

Each school gets a [school]-theme.css which contains:
```css
:root {
	--school-primary-color: color;
	--school-secondary-color: color;
	...
}
```

The existing stylesheets replace the Regis red colors with variable references

Pug layout template picks school stylesheet *(or a default one if not logged in)*
